extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
env:
  es6: true
  browser: true
globals:
  expect: true
  it: true
  describe: true
  jest: true
  afterEach: true
  beforeEach: true
parser: babel-eslint
rules:
  strict: 0
  # Disable this for now. Drupal does not use camel case properties and to make
  # code more simple, we are using Drupal's field names in forms, etc.
  camelcase: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  # The video and audio elements in this application are just previewers.
  jsx-a11y/media-has-caption: 0
  import/prefer-default-export: 0
