extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
env:
  es6: true
  browser: true
globals:
  expect: true
  it: true
  describe: true
  jest: true
parser: babel-eslint
rules:
  strict: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
